# Generated by Django 5.1.4 on 2025-01-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportInfo',
            new_name='GenreralInfo',
        ),
    ]
