# Generated by Django 5.1.4 on 2025-01-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_importinfo_genreralinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreralInfo',
            new_name='GeneralInfo',
        ),
    ]
