# Generated by Django 5.1.4 on 2025-01-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_genreralinfo_generalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='working_url',
        ),
    ]
