# Generated by Django 5.1.4 on 2025-01-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
