# Generated by Django 5.1.4 on 2025-01-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contactformllog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactFormlLog',
            new_name='ContactFormLog',
        ),
    ]
